# ---- Specify Models ----

# ---- ECSI ----
# load package
library("semPLS")

# get data
data(ECSImobi)

# rename model
ecsi.plsm <- ECSImobi

# rename dataframe
ecsi.data <- mobi

# remove unused objects
rm("ECSImm", "ECSIsm", "ECSImobi", "mobi")

# estimate model
ecsi.sempls <- sempls(ecsi.plsm, ecsi.data)

# get coefficinets
scoeffs <- ecsi.sempls$path_coefficients
# set nobs
nobs <- 200
# simulate random normal distributed residuals
sresid <- matrix(rnorm(mendo * nobs, mean=0, sd=1), mendo, nobs)


# transform upper to lower matrix
scoeffs[lower.tri(scoeffs)] <- t(scoeffs)[lower.tri(scoeffs)]
scoeffs[upper.tri(scoeffs)] <- 0

#' Simulate factor scores on given path coefficients and residuals.
#' 
#' @param latent        : character of latent variables
#'        strucmod      : 2 column "source", "target" matrix of structural model 
#'        nobs          : number of observations
#'        strucmod.lm   : list of lm objects generated by RefitStrucmod()
#' @return A matrix of simulated factor scores
#' @examples
#' sim_fscores(latent, strucmod, nobs, strucmod.lm)
sim_fscores <- function(nobs, scoeffs, sresid) { 
    
    # get number of exogenous latent variables
    mexo <- sum(rowSums(scoeffs) == 0)
    
    # get number of endogenous latent variables
    mendo <- ncol(scoeffs)-mexo
    
    # simulate random exogenous scores
    exo.scores <- matrix(rnorm(mexo * nobs, mean=0, sd=1), mexo, nobs)
    
    # set exogenous column names
    rownames(exo.scores) <- names(which(rowSums(scoeffs) == 0))
    
    # initialize endgenous scores
    endo.scores <- matrix(0, mendo, nobs)
    
    # set endogenous column names
    rownames(endo.scores) <- names(which(rowSums(scoeffs) != 0))
    
    result <- rbind(exo.scores, endo.scores)
    
    for(i in 1:nrow(endo.scores)){
    
        endo.scores[i, ] <- scoeffs[i+mexo, ] %*% result + sresid[i, ]  
    }
    
    result <- t(rbind(exo.scores, endo.scores))
    
    return(result)
    
    
}