#' Simulate a dataset on given factor scores, loadings and residuals.
#' 
#' @param manifest      : character of manifest variables
#'        strucmod      : 2 column "source", "target" matrix of structural model 
#'        sim.fscores   : matrix of simulated factor scores returned by SimStrucmod()
#'        nobs          : number of observations
#'        measuremod.lm : list of lm objects generated by RefitMeasuremod()
#' @return A simulated data matrix which fits the given model
#' @examples
#' sim_data(manifest, measuremod, sim.fscores, nobs, measuremod.lm)
sim_data <- function(manifest, measuremod, sim.fscores, nobs, 
                    mcoeffs, mresid) { 
    

    # get independent latent variable names
    indpndt.latent <- measuremod[, 1]
    
    # initialize result dataset
    result <- matrix(NA, nobs, length(manifest))  
    
    # set column names
    colnames(result) <- manifest
    
    for(i in seq_along(manifest)){
        
        result[, i] <- sim.fscores[, indpndt.latent[i]] * mcoeffs[i] + mresid[, i]
    }
    
    return(result) 
    
}

