#' Simulate factor scores on given path coefficients and residuals.
#' 
#' @param latent        : character of latent variables
#'        strucmod      : 2 column "source", "target" matrix of structural model 
#'        nobs          : number of observations
#'        strucmod.lm   : list of lm objects generated by RefitStrucmod()
#' @return A matrix of simulated factor scores
#' @examples
#' sim_fscores(latent, strucmod, nobs, strucmod.lm)
sim_fscores <- function(latent, strucmod, nobs, scoeffs.list, sresid) { 
    
    # get endogenous latent variable names
    endogenous <- unique(strucmod[, 2])
    
    # get exogenous latent variable names
    exogenous <- setdiff(latent, strucmod[, 2])   
    
    # get number of exogenous latent variables
    mexo <- length(exogenous)
    
    # simulate random score for exogenous latent variable(s)
    exo.scores <- matrix(rnorm(nobs * mexo, mean=0, sd=1), nobs, mexo)
    
    # set exogenous column names
    colnames(exo.scores) <- exogenous
    
    # initialize endgenous scores
    endo.scores <- matrix(numeric(), nobs, length(endogenous))
    
    # set endogenous column names
    colnames(endo.scores) <- endogenous
    
    # initialize simulated factor scores
    result <- cbind(exo.scores, endo.scores)
    
    # initialize index 
    i <- 1
    
    # initialize result index 
    j <- length(exogenous) + 1
    
    # estimate new endogenous factor scores
    for (dpndnt in endogenous) {
        
        # get index/indices of endogenous/target latent variable in strucmod
        dpndnt.index <- which(dpndnt == strucmod[, 2])
        
        # get corresponding name(s) of independent/source latent variable(s)
        indpnt <- strucmod[dpndnt.index, 1]  
        
        # solve structural model with simulated exogenous scores
        ifelse(length(scoeffs.list[[i]]) > 1, 
               result[, j] <- rowSums(t(t(result[, indpnt]) * scoeffs.list[[i]])) + sresid[, i], 
               result[, j] <- result[, indpnt] * scoeffs.list[[i]] + sresid[, i])
        
        # increment index by 1
        i <- i + 1
        
        # increment result index by 1
        j <- j + 1
        
    }
    
    return(result)

    
}